"""add language to user tests

Revision ID: 0c3a26dd7830
Revises: 4cdb12bddcda
Create Date: 2025-06-04 10:27:25.684923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3a26dd7830'
down_revision: Union[str, None] = '4cdb12bddcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tests', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tests', 'language')
    # ### end Alembic commands ###
