"""add user_tests and user_test_char_logs tables

Revision ID: 0c4b5a75ffa6
Revises: 06731b51752d
Create Date: 2025-06-02 11:24:42.597502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4b5a75ffa6'
down_revision: Union[str, None] = '06731b51752d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('wpm', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tests_id'), 'user_tests', ['id'], unique=False)
    op.create_index(op.f('ix_user_tests_user_id'), 'user_tests', ['user_id'], unique=False)
    op.create_table('user_test_char_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('char', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['user_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_test_char_logs_id'), 'user_test_char_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_test_char_logs_test_id'), 'user_test_char_logs', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_test_char_logs_test_id'), table_name='user_test_char_logs')
    op.drop_index(op.f('ix_user_test_char_logs_id'), table_name='user_test_char_logs')
    op.drop_table('user_test_char_logs')
    op.drop_index(op.f('ix_user_tests_user_id'), table_name='user_tests')
    op.drop_index(op.f('ix_user_tests_id'), table_name='user_tests')
    op.drop_table('user_tests')
    # ### end Alembic commands ###
