"""User customization uid fix

Revision ID: 113fb4737d14
Revises: c476622aac21
Create Date: 2025-06-03 00:40:32.238431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113fb4737d14'
down_revision: Union[str, None] = 'c476622aac21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_customizations_id', table_name='user_customizations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_customizations_id', 'user_customizations', ['id'], unique=False)
    # ### end Alembic commands ###
