"""add typing metrics

Revision ID: 209994c003d5
Revises: 0c4b5a75ffa6
Create Date: 2025-06-02 12:54:29.579150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209994c003d5'
down_revision: Union[str, None] = '0c4b5a75ffa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tests', sa.Column('raw_wpm', sa.Float(), nullable=False))
    op.add_column('user_tests', sa.Column('consistency', sa.Float(), nullable=False))
    op.add_column('user_tests', sa.Column('chars', sa.JSON(), nullable=False))
    op.add_column('user_tests', sa.Column('restarts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tests', 'restarts')
    op.drop_column('user_tests', 'chars')
    op.drop_column('user_tests', 'consistency')
    op.drop_column('user_tests', 'raw_wpm')
    # ### end Alembic commands ###
