"""Gammification

Revision ID: 5448b0300150
Revises: 0c3a26dd7830
Create Date: 2025-06-04 17:20:59.619358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5448b0300150'
down_revision: Union[str, None] = '0c3a26dd7830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('users', 'total_xp')
    # ### end Alembic commands ###
