"""User customization

Revision ID: 8ed164d3e1ae
Revises: 209994c003d5
Create Date: 2025-06-03 00:25:05.568094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed164d3e1ae'
down_revision: Union[str, None] = '209994c003d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_customizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('accent', sa.String(), nullable=True),
    sa.Column('cursor', sa.String(), nullable=True),
    sa.Column('cursor_blink', sa.Boolean(), nullable=True),
    sa.Column('char_fill', sa.Boolean(), nullable=True),
    sa.Column('sounds', sa.Boolean(), nullable=True),
    sa.Column('sound_set', sa.String(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('font', sa.String(), nullable=True),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('key_highlight', sa.Boolean(), nullable=True),
    sa.Column('on_screen_keyboard', sa.Boolean(), nullable=True),
    sa.Column('animations', sa.Boolean(), nullable=True),
    sa.Column('show_stats', sa.Boolean(), nullable=True),
    sa.Column('show_progress', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_customizations_id'), 'user_customizations', ['id'], unique=False)
    op.create_index('ix_user_test_char_logs_test_char', 'user_test_char_logs', ['test_id', 'char'], unique=False)
    op.create_index(op.f('ix_user_tests_timestamp'), 'user_tests', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tests_timestamp'), table_name='user_tests')
    op.drop_index('ix_user_test_char_logs_test_char', table_name='user_test_char_logs')
    op.drop_index(op.f('ix_user_customizations_id'), table_name='user_customizations')
    op.drop_table('user_customizations')
    # ### end Alembic commands ###
