"""Gammification Tables

Revision ID: bae92121f449
Revises: 5448b0300150
Create Date: 2025-06-04 17:41:11.061582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae92121f449'
down_revision: Union[str, None] = '5448b0300150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('max_streak', sa.Integer(), nullable=True),
    sa.Column('last_test_date', sa.DateTime(), nullable=True),
    sa.Column('total_tests_completed', sa.Integer(), nullable=True),
    sa.Column('total_words_typed', sa.Integer(), nullable=True),
    sa.Column('total_characters_typed', sa.Integer(), nullable=True),
    sa.Column('best_wpm', sa.Integer(), nullable=True),
    sa.Column('best_accuracy', sa.Integer(), nullable=True),
    sa.Column('total_typing_time_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_game_stats_id'), 'user_game_stats', ['id'], unique=False)
    op.create_index(op.f('ix_user_game_stats_user_id'), 'user_game_stats', ['user_id'], unique=True)
    op.create_table('xp_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('base_xp', sa.Integer(), nullable=True),
    sa.Column('wpm_bonus', sa.Integer(), nullable=True),
    sa.Column('accuracy_bonus', sa.Integer(), nullable=True),
    sa.Column('difficulty_bonus', sa.Integer(), nullable=True),
    sa.Column('length_bonus', sa.Integer(), nullable=True),
    sa.Column('streak_bonus', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['user_tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_logs_id'), 'xp_logs', ['id'], unique=False)
    op.create_index(op.f('ix_xp_logs_test_id'), 'xp_logs', ['test_id'], unique=False)
    op.create_index(op.f('ix_xp_logs_user_id'), 'xp_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xp_logs_user_id'), table_name='xp_logs')
    op.drop_index(op.f('ix_xp_logs_test_id'), table_name='xp_logs')
    op.drop_index(op.f('ix_xp_logs_id'), table_name='xp_logs')
    op.drop_table('xp_logs')
    op.drop_index(op.f('ix_user_game_stats_user_id'), table_name='user_game_stats')
    op.drop_index(op.f('ix_user_game_stats_id'), table_name='user_game_stats')
    op.drop_table('user_game_stats')
    # ### end Alembic commands ###
